site_name: SatLomas
site_description: Documentación de SatLomas
site_url: https://dymaxionlabs.github.io/satlomas-docs/
repo_url: https://github.com/dymaxionlabs/satlomas-docs/
nav:
    - Inicio: index.md
    - Guía de Uso: usage.md
    - Metodología: methodology.md
    - Implementación: deploy.md
theme:
    name: material
    language: es
    palette:
        primary: teal
        accent: pink
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.superfences:
        custom_fences:
            - name: 'mermaid'
              class: 'mermaid'
              format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js
