site_name: SatLomas
site_description: Documentación de SatLomas
site_url: https://dymaxionlabs.github.io/satlomas-docs/
repo_url: https://github.com/dymaxionlabs/satlomas-docs/
nav:
    - Inicio: index.md
    - Uso: usage.md
    - Metodología: methodology.md
    - Desarrollo: development.md
    - Implementación: deploy.md
theme:
    name: material
    language: es
    palette:
        primary: teal
        accent: pink
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.tabbed